controller_list:
  - name: fake_left_arm_controller
    type: $(arg execution_type)
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_arm_yaw
      - l_elbow_pitch
      - l_forearm_yaw
      - l_wrist_pitch
      - l_wrist_roll
  - name: fake_right_arm_controller
    type: $(arg execution_type)
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_arm_yaw
      - r_elbow_pitch
      - r_forearm_yaw
      - r_wrist_pitch
      - r_wrist_roll
  - name: fake_r_gripper_controller
    type: $(arg execution_type)
    joints:
      - r_gripper
  - name: fake_l_gripper_controller
    type: $(arg execution_type)
    joints:
      - l_gripper

  - name: fake_head_controller
    type: $(arg execution_type)
    joints:
      - bottom2middle
      - middle2top
      - bottom2middle

initial:  # Define initial robot poses.
  - group: left_arm
    pose: left_rest
  - group: right_arm
    pose: right_rest
  - group: l_gripper
    pose: l_gripper_rest
  - group: r_gripper
    pose: r_gripper_rest
  - group: head
    pose: head_rest
