gazebo_ros_control:
 pid_gains:
  r_shoulder_pitch:
    p: 100.0
    i: 0.0
    d: 1.0
    i_clamp: 0.2
    antiwindup: false
    publish_state: true
  r_shoulder_roll:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  r_arm_yaw:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  r_elbow_pitch:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  r_forearm_yaw:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  r_wrist_pitch:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  r_wrist_roll:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true

  l_shoulder_pitch:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  l_shoulder_roll:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  l_arm_yaw:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  l_elbow_pitch:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  l_forearm_yaw:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  l_wrist_pitch:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  l_wrist_roll:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true

  l_gripper:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  r_gripper:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true

  top2head:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  middle2top:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true
  bottom2middle:
    p: 100.0
    i: 0.0
    d: 1.0
    antiwindup: false
    publish_state: true